# -*- coding: utf-8 -*-
"""BuscaGulosaEAStar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18jYGeo7cLvVKc-HK3XVPKZLeAGrGHlfl

# Busca Gulosa
"""

distancias_em_linha_reta = {
    'Arad': 366,
    'Bucharest': 0,
    'Craiova': 160,
    'Drobeta': 242,
    'Fagaras': 178,
    'Lugoj': 244,
    'Mehadia': 241,
    'Oradea': 380,
    'Pitesti': 98,
    'Rimnicu Vilcea': 193,
    'Sibiu': 253,
    'Timisoara': 329,
    'Zerind': 374
}

grafo = {
    'Arad': {'Zerind': 75, 'Sibiu': 140, 'Timisoara': 118},
    'Zerind': {'Arad': 75, 'Oradea': 71},
    'Oradea': {'Zerind': 71, 'Sibiu': 151},
    'Sibiu': {'Arad': 140, 'Oradea': 151, 'Fagaras': 99, 'Rimnicu Vilcea': 80},
    'Timisoara': {'Arad': 118, 'Lugoj': 111},
    'Lugoj': {'Timisoara': 111, 'Mehadia': 70},
    'Mehadia': {'Lugoj': 70, 'Drobeta': 75},
    'Drobeta': {'Mehadia': 75, 'Craiova': 120},
    'Craiova': {'Drobeta': 120, 'Rimnicu Vilcea': 146, 'Pitesti': 138},
    'Rimnicu Vilcea': {'Sibiu': 80, 'Craiova': 146, 'Pitesti': 97},
    'Fagaras': {'Sibiu': 99, 'Bucharest': 211},
    'Pitesti': {'Rimnicu Vilcea': 97, 'Craiova': 138, 'Bucharest': 101},
    'Bucharest': {'Fagaras': 211, 'Pitesti': 101}
}

def busca_gulosa(origem, destino):
    caminho = [origem]
    cidade_atual = origem

    while cidade_atual != destino:
        print(f"Estou em {cidade_atual}, explorando opções...")

        # Pega todas as cidades vizinhas
        vizinhos = grafo[cidade_atual].keys()

        if not vizinhos:
            print("Sem saída - caminho bloqueado")
            return None

        # Escolhe o vizinho com menor distância em linha reta até o destino (heurística)
        proxima_cidade = min(vizinhos, key=lambda cidade: distancias_em_linha_reta[cidade])

        print(f"Vou para {proxima_cidade} (distância estimada: {distancias_em_linha_reta[proxima_cidade]})")

        caminho.append(proxima_cidade) #append final da lista
        cidade_atual = proxima_cidade

    print("\nCheguei ao destino!")
    return caminho

partida = 'Arad'
chegada = 'Bucharest'
print(f"\nBusca gulosa de {partida} para {chegada}:")
resultado = busca_gulosa(partida, chegada)
print("\nCaminho encontrado:", " -> ".join(resultado))

"""# A *"""

import heapq

distancias_em_linha_reta = {
    'Arad': 366,
    'Bucharest': 0,
    'Craiova': 160,
    'Drobeta': 242,
    'Fagaras': 178,
    'Lugoj': 244,
    'Mehadia': 241,
    'Oradea': 380,
    'Pitesti': 98,
    'Rimnicu Vilcea': 193,
    'Sibiu': 253,
    'Timisoara': 329,
    'Zerind': 374
}


grafo = {
    'Arad': {'Zerind': 75, 'Sibiu': 140, 'Timisoara': 118},
    'Zerind': {'Arad': 75, 'Oradea': 71},
    'Oradea': {'Zerind': 71, 'Sibiu': 151},
    'Sibiu': {'Arad': 140, 'Oradea': 151, 'Fagaras': 99, 'Rimnicu Vilcea': 80},
    'Timisoara': {'Arad': 118, 'Lugoj': 111},
    'Lugoj': {'Timisoara': 111, 'Mehadia': 70},
    'Mehadia': {'Lugoj': 70, 'Drobeta': 75},
    'Drobeta': {'Mehadia': 75, 'Craiova': 120},
    'Craiova': {'Drobeta': 120, 'Rimnicu Vilcea': 146, 'Pitesti': 138},
    'Rimnicu Vilcea': {'Sibiu': 80, 'Craiova': 146, 'Pitesti': 97},
    'Fagaras': {'Sibiu': 99, 'Bucharest': 211},
    'Pitesti': {'Rimnicu Vilcea': 97, 'Craiova': 138, 'Bucharest': 101},
    'Bucharest': {'Fagaras': 211, 'Pitesti': 101}
}

def a_estrela(origem, destino):
    # Fila de prioridade: armazena (f_score, g_score, cidade, caminho)
    fila = []
    heapq.heappush(fila, (distancias_em_linha_reta[origem], 0, origem, [origem]))
    #Origem: 'Arad' (h = 366). Destino: 'Bucharest'
    #heapq.heappush(fila, (366, 0, 'Arad', ['Arad']))

    # Dicionário para registrar o menor custo real (g_score) encontrado para cada cidade
    custo_real = {cidade: float('inf') for cidade in grafo}
    custo_real[origem] = 0

    while fila:
        _, g_atual, cidade_atual, caminho = heapq.heappop(fila)

        print(f"\nEstou em {cidade_atual} (custo real: {g_atual})")

        if cidade_atual == destino:
            print("\nCheguei ao destino!")
            return caminho

        for vizinho, distancia in grafo[cidade_atual].items():
            novo_g = g_atual + distancia
            print(f"  Analisando {vizinho} (custo acumulado: {novo_g}, heurística: {distancias_em_linha_reta[vizinho]})")

            # Se encontramos um caminho melhor para este vizinho
            if novo_g < custo_real[vizinho]:
                custo_real[vizinho] = novo_g
                f_score = novo_g + distancias_em_linha_reta[vizinho]  # g + h
                novo_caminho = caminho + [vizinho]
                heapq.heappush(fila, (f_score, novo_g, vizinho, novo_caminho))
                print(f"    Adicionado à fila com f_score = {f_score}")

    return None

partida = 'Arad'
chegada = 'Bucharest'
print(f"\nAlgoritmo A* de {partida} para {chegada}:")
resultado = a_estrela(partida, chegada)
print("\nCaminho encontrado:", " -> ".join(resultado))