# -*- coding: utf-8 -*-
"""NumpyScipy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wOGA1pQVdI104q7q5OJN1-rRxtlHZyfc
"""

import numpy as np
x = np.array([1, 2, 3])         # vetor 1D
m = np.array([[1, 2], [3, 4]])  # matriz 2D
print(m)

media = np.mean([10, 20, 30])
mediana = np.median([1, 2, 3, 4, 5])
variância = np.var([10, 12, 14])
desvio = np.std([10, 12, 14])
print(f"Média: {media},Mediana: {mediana}, Variância: {variância}, Desvio Padrão: {desvio}")

""" Produto escalar de vetores ou multiplicação de matrizes"""

w = np.array([0.2, 0.5])
x = np.array([1, 2])
resultado = np.dot(w, x)  # 0.2*1 + 0.5*2 = 1.2
print(resultado)

# Geração de vetores aleatórios
x = np.random.rand(5)
y = np.random.randint(5)
print(y)

"""Criação de decisões condicionais – semelhante a um if vetorial, muito útil para rótulos em classificação."""

valores = np.array([0.7, 0.85, 0.95])
print(valores)
classificacao = np.where(valores > 0.9, 'ótimo', 'regular')
print(classificacao)

"""Índice do maior ou menor valor"""

probs = np.array([0.1, 0.3, 0.6])

classe_predita = np.argmax(probs)
print(classe_predita)

#np.sum(), np.max(), np.min()

dados = np.array([[1, 2], [3, 4]])
print(np.sum(dados))
print(np.max(dados))

"""Distribuição Normal"""

from scipy.stats import norm

media = 0.90
desvio = 0.02

# Qual a probabilidade de um modelo ter precisão menor que 0.88?
prob = norm.cdf(0.88, loc=media, scale=desvio)
print(f"Probabilidade de precisão < 0.88: {prob:.4f}")

"""Distribuição Binominal"""

from scipy.stats import binom

# Probabilidade de acertar exatamente 7 de 10 previsões com 80% de chance de acerto
prob = binom.pmf(k=7, n=10, p=0.8)
print(f"P(X = 7): {prob:}")

"""Distribuição de Poisson"""

from scipy.stats import poisson

# Qual a chance de ocorrerem exatamente 3 erros, sabendo que a média é 2 por hora?
prob = poisson.pmf(k=3, mu=2)
print(f"P(X = 3): {prob:}")