# -*- coding: utf-8 -*-
"""PandasPythpn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xnzf0DlgEi5BV8PL6oGc5FWOHfpH9gbM

#Limpeza e Transformação de Dados. Manipulação de dados com Python: Pandas.
"""

import pandas

data = pandas.DataFrame({"A": [1, 2, 3]})

print(data)

"""Etapas da Limpeza de Dados"""

import pandas as pd

data = {
    'Nome': ['Ana', 'Bruno', 'Carlos', None, 'Ana'],
    'Idade': [23, None, 30, 25, 23],
    'Salário': [4000, 5000, None, 3500, 4000],
    'Cidade': ['São Paulo', 'São Paulo', 'Rio', 'Belo Horizonte', 'São Paulo']
}

df = pd.DataFrame(data)

print("Dados Originais:")

print(df)

"""Identificar Valores Ausentes"""

print("\nVerificando valores ausentes:")
print(df.isnull())
print("\nQuantidade de valores ausentes por coluna:")
print(df.isnull().sum())

# Removendo linhas com valores ausentes
df_cleaned = df.dropna()
print("\nDados após remover linhas com valores ausentes:")
print(df_cleaned)

# Preenchendo valores ausentes na coluna 'Idade' com a média
df['Idade'] = df['Idade'].fillna(df['Idade'].mean())
print("\nDados após preencher valores ausentes em 'Idade':")
print(df)

"""Removendo Duplicatas"""

print("\nLinhas duplicadas:")
print(df.duplicated())

# Removendo duplicatas
df = df.drop_duplicates()
print("\nDados após remover duplicatas:")
print(df)

"""Correção de Valores diferentes"""

# Converte todos os nomes para letras minúsculas (str.lower())
df['Cidade'] = df['Cidade'].str.lower()

print("\nDados com padronização de cidades:")
print(df)

"""Ler arquivo excel externo com Pandas"""

import pandas as pd

df2 = pd.read_excel('arquivo.xlsx')

print(df2.head())

"""Outras manipulações de dados com pandas"""

df['Salário Anual'] = df['Salário'] * 12

df_filtrado = df[df['Idade'] > 25]

df = df[['Nome', 'Cidade', 'Idade', 'Salário', 'Salário Anual']]

print("\nDataFrame após criar 'Salário Anual':")
print(df)
print("\nDataFrame filtrado (Idade > 25):")
print(df_filtrado)