# -*- coding: utf-8 -*-
"""Matplotlib_Seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BjGYWf26PU8_NSYCu7A-4hZ5gblsK2-M

Matplotlib
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 10, 20)     # 20 pontos entre 0 e 10
y = np.sin(x)                  # seno de x
categorias = ['A', 'B', 'C', 'D']
valores = [5, 7, 3, 4]
dados = np.random.randn(100)   # 100 números aleatórios (distribuição normal)

#  Gráfico de Linha
plt.figure(figsize=(10,6))
plt.subplot(2,3,1)
plt.plot(x, y, marker='o')
plt.title("plot(): Linha")

#  Gráfico de Dispersão
plt.subplot(2,3,2)
plt.scatter(x, y, color="red")
plt.title("scatter(): Dispersão")

#  Gráfico de Barras
plt.subplot(2,3,3)
plt.bar(categorias, valores, color="green")
plt.title("bar(): Barras")

#  Histograma
plt.subplot(2,3,4)
plt.hist(dados, bins=10, color="orange", edgecolor="black")
plt.title("hist(): Histograma")

# Gráfico de Caixa (Boxplot)
plt.subplot(2,3,5)
plt.boxplot(dados)
plt.title("boxplot(): Caixa")

plt.tight_layout()
plt.show()

"""Se"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

df = pd.DataFrame({
    "Categoria": ["A", "A", "B", "B", "C", "C"],
    "X": [1, 2, 3, 4, 5, 6],
    "Y": [2, 4, 1, 3, 5, 7],
    "Valor": [5, 7, 6, 8, 5, 9]
})

# Dispersão
sns.scatterplot(x="X", y="Y", hue="Categoria", data=df)
plt.title("scatterplot: Dispersão")
plt.show()

# Linha
sns.lineplot(x="X", y="Y", data=df, marker="o")
plt.title("lineplot: Linha")
plt.show()

# Barras
sns.barplot(x="Categoria", y="Valor", data=df)
plt.title("barplot: Barras")
plt.show()

# Histograma
sns.histplot(df["Valor"], bins=5, color="orange")
plt.title("histplot: Histograma")
plt.show()

# Densidade
sns.kdeplot(df["Valor"], fill=True, color="purple")
plt.title("kdeplot: Densidade")
plt.show()

# Boxplot
sns.boxplot(x="Categoria", y="Valor", data=df)
plt.title("boxplot: Caixa")
plt.show()

# Heatmap (correlação)
corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("heatmap: Mapa de Calor")
plt.show()

# Pairplot
sns.pairplot(df[["X", "Y", "Valor"]], diag_kind="kde")
plt.suptitle("pairplot: Relações entre variáveis", y=1.02)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

iris = sns.load_dataset("iris")
print(iris.head())
plt.figure(figsize=(6,4))
sns.heatmap(iris.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Mapa de Calor - Correlação das variáveis do Iris")
plt.show()

sns.pairplot(iris, hue="species")
plt.suptitle("Relação entre variáveis no Iris", y=1.02)
plt.show()