# -*- coding: utf-8 -*-
"""ArvoreDeDecisao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oAgC8NnWSBkscDbDPjeN0hJ7yUN1myDk
"""

import pandas as pd
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt

data = {
    'Peso': [150, 170, 140, 130, 155, 135, 165, 145],
    'Textura': [1, 0, 1, 0, 1, 0, 0, 1],
    'Fruta': ['maçã', 'laranja', 'maçã', 'laranja', 'maçã', 'laranja', 'laranja', 'maçã']
}

df = pd.DataFrame(data)

X = df[['Peso', 'Textura']]
y = df['Fruta']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

modelo = DecisionTreeClassifier(criterion='gini', max_depth=2, random_state=42)
modelo.fit(X_train, y_train)

y_pred = modelo.predict(X_test)

print("Acurácia:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

plt.figure(figsize=(8,6))
plot_tree(modelo, feature_names=X.columns, class_names=modelo.classes_, filled=True)
plt.show()


novo_dado = pd.DataFrame({'Peso': [160], 'Textura': [1]})

nova_predicao = modelo.predict(novo_dado)

print("Previsão para o novo dado:", nova_predicao[0])

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
import matplotlib.pyplot as plt

# A base Iris contém medidas de flores da espécie Iris, coletadas por botânicos. O objetivo é prever a espécie da flor com base nas medidas de suas partes.
iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

modelo = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state=42)
modelo.fit(X_train, y_train)

y_pred = modelo.predict(X_test)

print("Acurácia:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=iris.target_names))

plt.figure(figsize=(12,8))
plot_tree(modelo, feature_names=iris.feature_names, class_names=iris.target_names, filled=True)
plt.show()