# -*- coding: utf-8 -*-
"""Atividade - 06-10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q410_la55FhjxkgZ7qnGBFTyeU6H-nzh

# Atividade 06/10

- Escolha uma base de dados (do Scikit-learn, do Kaggle ou um arquivo CSV).

- Faça o carregamento dos dados, selecione colunas que sirvam como atributos de
entrada (X) e uma coluna como rótulo (y).

- Em seguida, divida os dados em treino e teste, treine um modelo de árvore de decisão com o Scikit-learn, avalie o desempenho do modelo (acurácia) e faça pelo menos três previsões para novos dados simulados.

- Mostre também a visualização da árvore.

Dataset: Passageiros do Titanic: https://www.kaggle.com/datasets/yasserh/titanic-dataset
"""

import pandas as pd
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "Titanic-Dataset.csv"

df = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "yasserh/titanic-dataset",
  file_path,
)

display(df.head())

df['Sex'] = df['Sex'].map({'male': 0, 'female': 1}) # Mapear sexos para boolean

df['Age'] = df['Age'].fillna(df['Age'].mean()) # Preencher nulls em 'Age' com a média

X = df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']]
Y = df['Survived']

Xtrain, Xtest, Ytrain, Ytest = train_test_split(X, Y, test_size= 0.2, random_state=42)

modelo = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state=42)
modelo.fit(Xtrain, Ytrain)

Ypred = modelo.predict(Xtest)

print("Acurácia: ", accuracy_score(Ytest, Ypred))
print(classification_report(Ytest, Ypred))

novoPassageiro1 = pd.DataFrame({
    'Pclass': [3],
    'Sex': [1],
    'Age': [25],
    'SibSp': [1],
    'Parch': [0],
    'Fare': [7.25]
})

novoPassageiro2 = pd.DataFrame({
    'Pclass': [1],
    'Sex': [0],
    'Age': [35],
    'SibSp': [1],
    'Parch': [0],
    'Fare': [71.2833]
})

novoPassageiro3 = pd.DataFrame({
    'Pclass': [3],
    'Sex': [0],
    'Age': [30],
    'SibSp': [0],
    'Parch': [0],
    'Fare': [7.925]
})

novoPredict1 = modelo.predict(novoPassageiro1)
novoPredict2 = modelo.predict(novoPassageiro2)
novoPredict3 = modelo.predict(novoPassageiro3)

print("Previsão do passageiro 1: ", novoPredict1[0])
print("Previsão do passageiro 2: ", novoPredict2[0])
print("Previsão do passageiro 3: ", novoPredict3[0])

plt.figure(figsize=(15, 10))
plot_tree(modelo, filled=True, feature_names=X.columns, class_names=['Morreu', 'Sobreviveu'])
plt.show()