# -*- coding: utf-8 -*-
"""Atividade-29-09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/178FWyaGNTOBtK6HI5f2OHzHQn5vdvD7m

# Atividade 29/09

Utilize o algoritmo K-Means para realizar o agrupamento de clientes com base nas colunas de idade, renda anual e pontuação de consumo.

- Leia os dados do seguinte arquivo CSV:

https://raw.githubusercontent.com/tirthajyoti/Machine-Learning-with-Python/master/Datasets/Mall_Customers.csv

- Selecione apenas as colunas numéricas necessárias para o agrupamento: Age, Annual Income (k$) e Spending Score (1-100).

- Aplique o K-Means com o melhor valor de k, determinado com base no método do cotovelo e no Silhouette Score.

- Adicione ao DataFrame a coluna com o número do cluster correspondente a cada cliente.

- Visualize os agrupamentos utilizando um gráfico de dispersão colorido por cluster.

- Por fim, exiba a inércia do modelo e utilize groupby() para mostrar as médias das variáveis por grupo e descrever os perfis de clientes encontrados.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

url = 'https://raw.githubusercontent.com/tirthajyoti/Machine-Learning-with-Python/master/Datasets/Mall_Customers.csv'
df = pd.read_csv(url)

X = df[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']]

# Método do Cotovelo
inertia = []
for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8, 5))
plt.plot(range(1, 11), inertia, marker='o')
plt.title('Método do Cotovelo')
plt.xlabel('Número de Clusters (k)')
plt.ylabel('Inércia')
plt.grid(True)
plt.show()

# Silhouette Score

silhouette_scores = []

for k in range(2, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    labels = kmeans.fit_predict(X)
    score = silhouette_score(X, labels)
    silhouette_scores.append(score)
    print(f'k={k}, Silhouette Score = {score:.4f}')

plt.figure(figsize=(8, 5))
plt.plot(range(2, 11), silhouette_scores, marker='o')
plt.title('Silhouette Score para diferentes valores de k')
plt.xlabel('Número de Clusters (k)')
plt.ylabel('Silhouette Score')
plt.grid(True)
plt.show()

# Com base nos gráficos, o melhor k é 4 para este conjunto de dados
best_k = 4

kmeans = KMeans(n_clusters=best_k, random_state=42)
df['cluster'] = kmeans.fit_predict(X)

print(f"Inércia do modelo: {kmeans.inertia_}")

display(df.head())

import plotly.express as px
import plotly.graph_objects as go

fig = px.scatter_3d(df, x='Age', y='Annual Income (k$)', z='Spending Score (1-100)',
                    color='cluster', size_max=10, opacity=0.7,
                    title="Clusters de Clientes com K-Means")

centroids = kmeans.cluster_centers_
fig.add_trace(go.Scatter3d(x=centroids[:, 0], y=centroids[:, 1], z=centroids[:, 2],
                           mode='markers', marker=dict(size=10, color='red', symbol='x'),
                           name='Centróides'))

fig.update_layout(scene=dict(xaxis_title='Idade',
                             yaxis_title='Renda Anual',
                             zaxis_title='Pontuação de Consumo'),
                  legend_title='Cluster')

fig.show()

means = df.groupby('cluster')[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']].mean()
print("Médias das variáveis por cluster:")
print(means)

"""## Perfis de Clientes Encontrados:

Baseado nas médias por cluster, podemos descrever os seguintes perfis de clientes:

- **0**: Clientes adultos (45 anos), com renda moderada (49 k$) e pontuação de consumo média (43). Representam um grupo equilibrado.

- **1**: Clientes jovens adultos (33 anos), com alta renda (87 k$) e alta pontuação de consumo (82). São clientes com alto poder de compra e propensão a gastos elevados.

- **2**: Clientes jovens (25 anos), com baixa renda (29 k$) e alta pontuação de consumo (74). Terríveis gastadores impulsivos, que priorizam consumo apesar da renda limitada.

- **3**: Clientes adultos (40 anos), com alta renda (87 k$) e baixa pontuação de consumo (19). São cautelosos e poupadores.
"""