# -*- coding: utf-8 -*-
"""Atividade-22-09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f0wKX9QsbbwJQOpS_IuYa0s504iWLRYN
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression, LogisticRegression

"""# Atividade 1

Crie um conjunto de dados com com pelo menos 6 exemplos, onde exista uma relação entre uma variável independente (entrada) e uma variável dependente (saída).

Em seguida:

- Treine um modelo de regressão linear usando esses dados.

- Faça a previsão para um novo valor de entrada que você escolher.

- Mostre o valor previsto.
"""

dataLinear = {
    'orcamento': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
    'receita': [50, 80, 110, 140, 170, 200, 230, 260, 290, 320]
}

dfLinear = pd.DataFrame(dataLinear)

XLinear = dfLinear[['orcamento']]
YLinear = dfLinear['receita']

modelLinear = LinearRegression()
modelLinear.fit(XLinear, YLinear)

novoOrcamento = pd.DataFrame([[110]], columns=['orcamento'])
receitaPrevista = modelLinear.predict(novoOrcamento)
print(f"Receita de vendas prevista para orçamento de 110: {receitaPrevista[0]:.2f}")

"""# Atividade 2

Crie um conjunto de dados com pelo menos 6 exemplos, onde exista uma
variável de entrada (número) e uma variável de saída binária (classe 0 ou 1).

Em seguida:

- Treine um modelo de regressão logística usando esses dados.
- Faça a previsão para um novo valor de entrada que você escolher.
- Mostre a classe prevista (0 ou 1).
"""

dataLogistico = {
    'creditScore': [500, 550, 600, 620, 650, 680, 700, 720, 750, 800],
    'aprovado': [0, 0, 0, 0, 1, 1, 1, 1, 1, 1]
}

dfLogistico = pd.DataFrame(dataLogistico)

XLogistico = dfLogistico[['creditScore']]
YLogistico = dfLogistico['aprovado']

modelLogistico = LogisticRegression()
modelLogistico.fit(XLogistico, YLogistico)

novoScore = pd.DataFrame([[660]], columns=['creditScore'])
previsaoAprovado = modelLogistico.predict(novoScore)
print(f"Aprovação prevista para nota de crédito 660: {previsaoAprovado[0]}")